### ISSUE TITLE
Does This Work?

### ISSUE THREAD

**Issue by metaskills** [QuinnyPig/tailscale-layer#2]
Hey @QuinnyPig, hope you're doing well. I'm working on a Lambda Container extension based off this work and I am having one hell of a time getting it working. Can someone validate for me Tailscale does indeed work in Lambda... via some method?

**Comment by quinnypig** [comment]
It absolutely does, and this *was* working when I wrote it. Pop into
https://slack.lastweekinaws.com and let’s see what broke.

**Comment by metaskills** [comment]
Thanks, pinged you on Twitter to figure out how to get in.

**Comment by metaskills** [comment]
Closing this out, I was being dumb and was trying to access my tailnet directly vs. using the SOCKS5 proxy. I made longer callout to this in my fork of the project which uses container packages vs Lambda layers. Thank you Corey!

https://github.com/rails-lambda/tailscale-extension#usage
